<!--
  ~ Copyright 2024 Oracle and/or its affiliates
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ https://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<!DOCTYPE data-dictionary [
        <!ELEMENT data-dictionary (statement-execution-processor)*>
        <!ELEMENT statement-execution-processor (statement)*>
        <!ATTLIST statement-execution-processor
                id CDATA #REQUIRED
                is-query CDATA #IMPLIED>
        <!ELEMENT statement (#PCDATA)>
        <!ATTLIST statement
                comment CDATA #IMPLIED
                variants CDATA #IMPLIED>
        ]>
<data-dictionary>
    <statement-execution-processor id="create-view">
        <statement>create view {0} as {1}</statement>
    </statement-execution-processor>

    <statement-execution-processor id="change-view">
        <statement>create or replace view {0} as {1}</statement>
    </statement-execution-processor>





    <statement-execution-processor id="create-object">
        <statement>create {0}</statement>
    </statement-execution-processor>

    <statement-execution-processor id="change-object">
        <statement>create or replace {0}</statement>
    </statement-execution-processor>

    <statement-execution-processor id="change-java-object">
        <statement>
            begin
                execute immediate 'create or replace java source named {0} as {1}';
            end;
        </statement>
    </statement-execution-processor>
    
    <statement-execution-processor id="drop-object">
        <statement>drop {0} {1}.{2}</statement>
    </statement-execution-processor>

    <statement-execution-processor id="drop-object-body">
        <statement>drop {0} body {1}.{2}</statement>
    </statement-execution-processor>

    <statement-execution-processor id="drop-java-object">
        <statement>
            begin
              dbms_java.dropjava('{0}.{1}');
            end;
        </statement>
        <statement>
            begin
                execute immediate 'drop java source {0}.{1}';
            exception
            when others then
                execute immediate 'drop java class {0}.{1}';
            end;
        </statement>
    </statement-execution-processor>

</data-dictionary>